import "./globals.css";
import type { Metadata } from "next";
import Header from '@/app/components/layout/Header/Header';
import Footer from '@/app/components/layout/Footer';
import localFont from 'next/font/local';
import { Bodoni_Moda } from 'next/font/google';
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Kumar Properties | Crafting Homes",
  description: "Generational Legacy since 1966.",
};

// 1. Setup Local Brand Font (Nexa)
const nexa = localFont({
  src: [
    {
      path: './fonts/NEXAREGULAR.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/NEXABOLD.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/NEXABLACK.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-nexa',
  display: 'swap',
});

// 2. Setup Google Font (Bodoni Moda)
const bodoni = Bodoni_Moda({ 
  subsets: ['latin'],
  style: ['italic'],
  variable: '--font-bodoni',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Inject the exact variables defined in globals.css, plus antialiased for crisp rendering
    <html lang="en">
      <body className="min-h-screen flex flex-col font-sans">
        <Header />
        
        <main className="flex-grow">
          {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}

// import "./globals.css";
// import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// import Header from '@/app/components/layout/Header/Header';
// import Footer from '@/app/components/layout/Footer';
// import Script from 'next/script';
// import localFont from 'next/font/local'
// import { Bodoni_Moda, Geist } from 'next/font/google'
// import { cn } from "@/lib/utils";

// const geist = Geist({subsets:['latin'],variable:'--font-sans'});


// // const geistSans = Geist({
// //   // variable: "--font-geist-sans",
// //   // subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   // variable: "--font-geist-mono",
// //   // subsets: ["latin"],
// // });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const nexa = localFont({
//   src: [
//     {
//       path: '../public/fonts/Nexa-Regular.woff2',
//       weight: '400',
//       style: 'normal',
//     },
//     {
//       path: '../public/fonts/Nexa-Bold.woff2',
//       weight: '700',
//       style: 'normal',
//     },
//     {
//       path: '../public/fonts/Nexa-Black.woff2',
//       weight: '900',
//       style: 'normal',
//     },
//   ],
//   variable: '--font-nexa',
//   display: 'swap',
// })

// // 2. Setup Google Font (Bodoni Moda)
// const bodoni = Bodoni_Moda({ 
//   subsets: ['latin'],
//   style: ['italic'],
//   variable: '--font-bodoni',
//   display: 'swap',
// })

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={cn("font-sans", geist.variable)}>
//       <body>
//         <Header />
//         {/* <main className="min-h-screen"> */}
//         {children}
//         {/* </main> */}
//         {/* <Footer /> */}

//         {/* 2. Add the Bootstrap JS Bundle right before the closing body tag */}
//         <Script
//           src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
//           strategy="lazyOnload"
//         />
//       </body>
//     </html>

//     // <html
//     //   lang="en"
//     //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     // >
//     //   <body className="min-h-full flex flex-col">
//     //     <Header />
//     //     {children}
//     //     <Footer />
//     //     <Script
//     //       src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
//     //       strategy="lazyOnload"
//     //     />
//     //   </body>
//     // </html>
//   );
// }
